baseURL: 'https://agramakov.me'
languageCode: 'en-us'
paginate: 3
theme: 'maverick'
title: 'Andrei Gramakov - Personal Page'

permalinks:
  pages: '/:slug'

params:
  author: 'Andrei Gramakov'
  description: 'Personal page of Andrei Gramakov'
  logo: '/assets/favicon.ico'
  comments:
    enabled: true
    githubRepo: 'canhtran/maverick'
    theme: 'github-light'

menu:
  main:
    - identifier: 'cv'
      name: 'CV'
      url: 'experience'
      weight: -110
    # - identifier: 'posts'
    #   name: 'Post'
    #   url: '/posts/'
    #   weight: -200

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: 'monokailight'
    tabWidth: 4

taxonomies:
  tag: 'tags'

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
  section:
    - 'HTML'

outputFormats:
  RSS:
    baseName: 'atom'
    mediatype: 'application/rss'
  JSON:
    baseName: 'feed'
    mediatype: 'application/json'

ignoreErrors:
  - 'error-remote-getjson'
