baseURL: 'https://agramakov.me'
languageCode: 'en-us'
paginate: 3
theme: 'maverick-mod'
title: 'Andrei Gramakov'

permalinks:
  pages: '/:slug'

params:
  author: 'Andrei Gramakov'
  description: 'Personal page of Andrei Gramakov'
  logo: '/assets/favicon-package/favicon.ico'
  comments:
    enabled: true
    githubRepo: 'canhtran/maverick'
    theme: 'github-light'

menu:
  main:
    - name: 'BLOG'
      url: 'https://agramakov.me/blog'
      weight: -100
      
    - name: 'CV PAGE'
      pageRef: /cv-online
      weight: -110
      
    #- name: 'CV PDF'
    #  url: 'https://agramakov.me/cv-pdf'
    #  weight: -110

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: 'monokailight'
    tabWidth: 4

taxonomies:
  tag: 'tags'

outputs:
  home:
    - 'HTML'
    - 'RSS'
    - 'JSON'
  section:
    - 'HTML'

outputFormats:
  RSS:
    baseName: 'atom'
    mediatype: 'application/rss'
  JSON:
    baseName: 'feed'
    mediatype: 'application/json'

ignoreErrors:
  - 'error-remote-getjson'
